name: HEDGE Reward System

on:
  workflow_dispatch:
    inputs:
      test_mode:
        required: true
        default: 'true'
  schedule:
    - cron: '0 15 * * 6'

jobs:
  hedge-rewards:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install Solana and Seed Phrase Libraries
        run: npm install @solana/web3.js @solana/spl-token bs58 bip39 ed25519-hd-key

      - name: Run Reward System
        # PARANDUS: Me suuname GitHub Secrets väärtuse otse siin käivitamise hetkel mällu sisse (env:)
        env:
          PAYER_SECRET_KEY: ${{ secrets.PAYER_SECRET_KEY }}
        run: NODE_OPTIONS="--no-addons" node snapshot.js
